import XCTest
@testable import QuaraMoney

/// Pins the wire contract between MitraTrip and QuaraMoney.
///
/// The two apps live in separate repositories and hand-mirror the payload
/// structs, so nothing but a real artifact proves they still agree. The base64
/// below was produced by MitraTrip's own `QuaraMoneyExport` encoder — if either
/// side's field names, nesting or date strategy drift, this test fails instead
/// of the feature silently doing nothing on a user's phone.
///
/// `decodePayload` is `try?`-based: a shape mismatch produces no error, no log
/// and no visible effect. That is precisely why this is asserted, not assumed.
final class MitraTripPayloadContractTests: XCTestCase {

    /// Generated by MitraTrip: a two-expense Siem Reap trip, USD, with location.
    private let mitraTripPayload = "eyJjYXRlZ29yeUtleSI6InRyaXAiLCJjdXJyZW5jeUNvZGUiOiJVU0QiLCJkYXRlIjoiMjAyNS0wNi0wNFQwMToyMDowMFoiLCJlbnRyaWVzIjpbeyJhbW91bnRNaW5vciI6MjUwMCwiY2F0ZWdvcnlLZXkiOiJmb29kX2RyaW5rIiwiZGF0ZSI6IjIwMjUtMDYtMDRUMDE6MjA6MDBaIiwic291cmNlSWQiOiJleHAtMSIsInRpdGxlIjoiRGlubmVyIGF0IE1hbGlzIn0seyJhbW91bnRNaW5vciI6MTc1MCwiY2F0ZWdvcnlLZXkiOiJ0cmFuc3BvcnRhdGlvbiIsImRhdGUiOiIyMDI1LTA2LTA1VDA1OjA2OjQwWiIsInNvdXJjZUlkIjoiZXhwLTIiLCJ0aXRsZSI6IlR1ay10dWsgdG8gQW5na29yIn1dLCJpc0N1c3RvbVNwbGl0Ijp0cnVlLCJsb2NhdGlvbiI6eyJkaXNwbGF5TmFtZSI6IlNpZW0gUmVhcCIsImZ1bGxBZGRyZXNzIjoiU2llbSBSZWFwLCBDYW1ib2RpYSIsImxhdGl0dWRlIjoxMy4zNjcxLCJsb25naXR1ZGUiOjEwMy44NDQ4LCJzaG9ydEFkZHJlc3MiOiJTaWVtIFJlYXAifSwibm90ZSI6IlNpZW0gUmVhcCIsIm9yaWdpbmFsQW1vdW50Ijo0Mi41LCJzb3VyY2UiOnsiYXBwIjoibWl0cmF0cmlwIiwiY3JlYXRlZEF0IjoiMjAyNS0wNi0xNVQxNTowNjo0MFoiLCJjdXJyZW5jeUV4cG9uZW50IjoyLCJ0b3RhbE1pbm9yIjo0MjUwLCJ0cmlwSWQiOiJ0cmlwLWFiYyIsInRyaXBOYW1lIjoiU2llbSBSZWFwIn0sInNwbGl0QW1vdW50Ijo0Mi41LCJzcGxpdENvdW50IjoxLCJ2ZXJzaW9uIjoyfQ"

    private var url: URL {
        URL(string: "quaramoney://split?data=\(mitraTripPayload)")!
    }

    func testDecodesPayloadProducedByMitraTrip() throws {
        let payload = try XCTUnwrap(
            SplitExpenseService.decodePayload(from: url),
            "MitraTrip's payload no longer decodes — the wire contract has drifted"
        )

        XCTAssertEqual(payload.version, 2)
        XCTAssertEqual(payload.currencyCode, "USD")
        XCTAssertTrue(payload.isDetailed)
        XCTAssertEqual(payload.entries?.count, 2)
    }

    func testSourceMetadataSurvives() throws {
        let payload = try XCTUnwrap(SplitExpenseService.decodePayload(from: url))
        let source = try XCTUnwrap(payload.source)

        XCTAssertEqual(source.app, "mitratrip")
        XCTAssertEqual(source.tripId, "trip-abc")
        XCTAssertEqual(source.tripName, "Siem Reap")
        XCTAssertEqual(source.currencyExponent, 2)
        XCTAssertEqual(source.totalMinor, 4_250)
    }

    /// The exported figure must equal what MitraTrip's Split tab displays.
    func testConsolidatedTotalMatchesSumOfEntries() throws {
        let payload = try XCTUnwrap(SplitExpenseService.decodePayload(from: url))
        let entrySum = (payload.entries ?? []).reduce(into: Int64(0)) { $0 += $1.amountMinor }

        XCTAssertEqual(entrySum, 4_250)
        XCTAssertEqual(payload.consolidatedAmount, Decimal(string: "42.50"))
    }

    func testEntryFieldsAndCategoryKeysSurvive() throws {
        let payload = try XCTUnwrap(SplitExpenseService.decodePayload(from: url))
        let entries = try XCTUnwrap(payload.entries)

        XCTAssertEqual(entries[0].sourceId, "exp-1")
        XCTAssertEqual(entries[0].title, "Dinner at Malis")
        XCTAssertEqual(entries[0].amountMinor, 2_500)
        XCTAssertEqual(entries[0].categoryKey, "food_drink")
        XCTAssertEqual(entries[1].categoryKey, "transportation")
    }

    /// Every category key MitraTrip can emit must resolve in the catalog,
    /// otherwise imports land in the fallback bucket and the user re-files
    /// them by hand.
    func testEveryMitraTripCategoryKeyExistsInCatalog() {
        let emitted = ["food_drink", "transportation", "leisure", "personal_lifestyle", "health", "trip"]
        for key in emitted {
            XCTAssertNotNil(
                CategoryCatalog.definition(forKey: key),
                "MitraTrip emits \(key), which is not in CategoryCatalog"
            )
        }
    }

    func testLocationSurvivesWhenOptedIn() throws {
        let payload = try XCTUnwrap(SplitExpenseService.decodePayload(from: url))
        let location = try XCTUnwrap(payload.location)

        XCTAssertEqual(location.displayName, "Siem Reap")
        XCTAssertEqual(location.latitude, 13.3671, accuracy: 0.0001)
        XCTAssertEqual(location.longitude, 103.8448, accuracy: 0.0001)
    }
}
