import SwiftData
import Foundation

@Model
final class Transaction {
    @Attribute(.unique) var id: UUID
    var type: TransactionType
    // Note: SwiftData indexing via @Attribute(.indexed) is not yet available
    // TODO: Add index when SwiftData supports it for faster date-range queries
    var date: Date
    var note: String?
    
    // Feature: Exclude from reports
    var excludeFromReports: Bool = false
    
    // Financials
    var amount: Decimal // Raw amount in original currency
    var currencyCode: String // Currency of the transaction
    var exchangeRate: Decimal // Conversion rate to Wallet's currency
    
    // Attachments
    var photoData: Data?
    
    // Relationships
    var category: Category? // Nil for transfers
    var event: Event?
    var sourceWallet: Wallet?
    var destinationWallet: Wallet? // Only for transfers
    var recurringRule: RecurringRule? // If generated by subscription
    
    init(amount: Decimal, currencyCode: String, date: Date, type: TransactionType, exchangeRate: Decimal = 1.0) {
        self.id = UUID()
        self.amount = amount
        self.currencyCode = currencyCode
        self.exchangeRate = exchangeRate
        self.date = date
        self.type = type
    }
}
