import SwiftUI
import SwiftData

struct RecurringRuleDetailView: View {
    @Environment(\.modelContext) private var modelContext
    
    let rule: RecurringRule
    @State private var showingEditRule = false
    @State private var transactionToEdit: Transaction?
    @State private var editingDueRule: RecurringRule?
    @State private var sortOption: TransactionSortOption = .newestFirst

    init(rule: RecurringRule) {
        self.rule = rule
    }

    /// True when this rule has an occurrence due today or earlier — i.e. it would
    /// appear in the review inbox and is waiting to be posted or skipped.
    private var isDue: Bool { RecurringRuleService.isDue(rule) }
    
    private var ruleColor: Color {
        rule.type == .income ? ThemeManager.shared.incomeColor : ThemeManager.shared.expenseColor
    }
    
    private var ruleIcon: String {
        rule.category?.icon ?? (rule.type == .income ? "arrow.down.left" : "arrow.up.right")
    }
    
    private var ruleAmountString: String {
        let formattedAmount = rule.amount.formattedAmount(for: rule.currencyCode)
        return rule.type == .income ? "+\(formattedAmount)" : "-\(formattedAmount)"
    }
    
    /// Transactions generated by this rule, loaded from the query.
    private var sortedTransactions: [Transaction] {
        let fetched = (rule.generatedTransactions ?? []).filter { $0.deletedAt == nil }
        
        let targetCurrency = CurrencyManager.shared.preferredCurrencyCode
        let rates = CurrencyManager.shared.rates
        
        switch sortOption {
        case .newestFirst:
            return fetched.sorted { $0.date > $1.date }
        case .oldestFirst:
            return fetched.sorted { $0.date < $1.date }
        case .highestAmount:
            return fetched.sorted { t1, t2 in
                let a1 = CurrencyManager.convert(amount: t1.amount, from: t1.currencyCode, to: targetCurrency, rates: rates)
                let a2 = CurrencyManager.convert(amount: t2.amount, from: t2.currencyCode, to: targetCurrency, rates: rates)
                if a1 == a2 { return t1.date > t2.date }
                return a1 > a2
            }
        case .lowestAmount:
            return fetched.sorted { t1, t2 in
                let a1 = CurrencyManager.convert(amount: t1.amount, from: t1.currencyCode, to: targetCurrency, rates: rates)
                let a2 = CurrencyManager.convert(amount: t2.amount, from: t2.currencyCode, to: targetCurrency, rates: rates)
                if a1 == a2 { return t1.date > t2.date }
                return a1 < a2
            }
        }
    }
    
    var body: some View {
        List {
            // Consolidated hero card: amount, frequency, status + wallet/category
            // and schedule details all in one card.
            Section {
                RecurringHeroCard(rule: rule, tint: ruleColor, icon: ruleIcon, amountString: ruleAmountString)
                    .listRowInsets(EdgeInsets()) // Expand to full row width — aligns with sections below
                    .listRowBackground(Color.clear)
                    .listRowSeparator(.hidden)
            }

            // Review / Due occurrence — mirrors the inbox so the user can post,
            // skip, edit-and-post, or pause this rule right from its detail page.
            if isDue {
                Section(L10n.Recurring.Review.title) {
                    RecurringDueRow(
                        rule: rule,
                        onPost: {
                            let posted = RecurringRuleService.post(rule: rule, in: modelContext)
                            HapticManager.shared.notification(type: posted == nil ? .error : .success)
                        },
                        onSkip: { RecurringRuleService.skip(rule: rule, in: modelContext) }
                    )
                    .swipeActions(edge: .leading) {
                        Button { editingDueRule = rule } label: {
                            Label(L10n.Recurring.editAndPost, systemImage: "slider.horizontal.3")
                        }
                        .tint(.blue)
                        Button { togglePause(rule) } label: {
                            Label(L10n.Recurring.pause, systemImage: "pause.circle")
                        }
                        .tint(.orange)
                    }
                }
            }

            // Transactions List
            let transactions = sortedTransactions
            if transactions.isEmpty {
                Section {
                    AppEmptyStateView(
                        L10n.Budget.noTransactions,
                        systemImage: "list.bullet.clipboard",
                        description: ""
                    )
                }
            } else {
                TransactionListView(
                    transactions: transactions,
                    sortOption: sortOption,
                    listHeader: L10n.FilteredTransactions.transactionsLabel,
                    onEdit: { txn in
                        transactionToEdit = txn
                    },
                    onDelete: { txn in
                        deleteTransaction(txn)
                    }
                )
            }
        }
        .listStyle(.insetGrouped)
        .navigationTitle(rule.name)
        .toolbar {
            ToolbarItemGroup(placement: .topBarTrailing) {
                // Sort Button
                Menu {
                    Picker(selection: $sortOption, label: Text(L10n.Sort.title)) {
                        ForEach(TransactionSortOption.allCases) { option in
                            Text(option.displayName).tag(option)
                        }
                    }
                } label: {
                    Image(systemName: "arrow.up.arrow.down")
                }
                .accessibilityLabel(L10n.Sort.title)
                
                // Edit Rule Button
                Button {
                    showingEditRule = true
                } label: {
                    Label(L10n.Common.edit, systemImage: "pencil")
                }
            }
        }
        .sheet(isPresented: $showingEditRule) {
            RecurringRuleEditorView(rule: rule)
        }
        .sheet(item: $transactionToEdit) { txn in
            AddTransactionContainer(transaction: txn, isNewTransaction: false)
        }
        .sheet(item: $editingDueRule) { rule in
            RecurringPostEditorView(rule: rule)
        }
    }

    /// Pauses (or resumes) the rule. Mirrors `RecurringRuleListView.togglePause`:
    /// on resume, fast-forward past elapsed occurrences and re-arm the reminder.
    private func togglePause(_ rule: RecurringRule) {
        rule.isActive.toggle()
        if rule.isActive {
            rule.nextDueDate = RecurringRuleService.resumedNextDueDate(for: rule)
        }
        rule.updatedAt = Date()
        rule.needsSync = true
        try? modelContext.save()
        NotificationCenter.default.post(name: .dataDidUpdate, object: nil)
        Task { await RecurringNotificationService.reschedule(for: rule) }
    }
    
    private func deleteTransaction(_ transaction: Transaction) {
        SoftDeleteService.deleteTransaction(transaction)
        do {
            try modelContext.save()
            NotificationCenter.default.post(name: .dataDidUpdate, object: nil)
        } catch {
            #if DEBUG
            print("Error deleting transaction: \(error)")
            #endif
        }
    }
}

// MARK: - Hero Card

/// A single consolidated card for a recurring rule: a tinted header with the
/// signed amount, frequency and status, over a clean list of schedule details
/// (category, wallet, next payment, start/end).
private struct RecurringHeroCard: View {
    let rule: RecurringRule
    let tint: Color
    let icon: String
    let amountString: String

    private var nextDueState: (text: String, color: Color) {
        let cal = Calendar.current
        let todayStart = cal.startOfDay(for: Date())
        if rule.nextDueDate < todayStart {
            return (L10n.Recurring.overdue, .white)
        } else if cal.isDateInToday(rule.nextDueDate) {
            return (L10n.Recurring.dueToday, .white)
        }
        return (rule.nextDueDate.formatted(date: .abbreviated, time: .omitted), .white.opacity(0.9))
    }

    var body: some View {
        VStack(spacing: 0) {
            header
            details
        }
        .clipShape(RoundedRectangle(cornerRadius: 24, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .strokeBorder(Color.primary.opacity(0.06), lineWidth: 0.5)
        )
        .shadow(color: tint.opacity(0.25), radius: 12, x: 0, y: 6)
    }

    // Tinted top zone.
    private var header: some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack(alignment: .top, spacing: 12) {
                Image(systemName: icon)
                    .font(.app(.title3, weight: .semibold))
                    .foregroundStyle(.white)
                    .frame(width: 48, height: 48)
                    .background(.white.opacity(0.22), in: RoundedRectangle(cornerRadius: 14, style: .continuous))

                VStack(alignment: .leading, spacing: 3) {
                    Text(rule.name)
                        .font(.app(.headline))
                        .foregroundStyle(.white)
                        .lineLimit(1)
                    Text(rule.frequency.displayName(interval: rule.interval))
                        .font(.app(.subheadline, weight: .medium))
                        .foregroundStyle(.white.opacity(0.85))
                }

                Spacer(minLength: 8)

                statusPill
            }

            VStack(alignment: .leading, spacing: 6) {
                HStack(alignment: .firstTextBaseline, spacing: 6) {
                    Text(amountString)
                        .font(.app(.largeTitle, weight: .bold))
                        .foregroundStyle(.white)
                        .lineLimit(1)
                        .minimumScaleFactor(0.6)
                    Text(rule.currencyCode)
                        .font(.app(.headline, weight: .semibold))
                        .foregroundStyle(.white.opacity(0.8))
                }

                if rule.isActive {
                    Label {
                        Text("\("recurring.nextPayment".localized) · \(nextDueState.text)")
                    } icon: {
                        Image(systemName: "calendar")
                    }
                    .font(.app(.footnote, weight: .medium))
                    .foregroundStyle(nextDueState.color)
                }
            }
        }
        .padding(20)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            LinearGradient(
                colors: [tint, tint.opacity(0.82)],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )
        )
    }

    @ViewBuilder
    private var statusPill: some View {
        if !rule.isActive {
            pill(text: L10n.Recurring.paused, systemImage: "pause.fill")
        } else if RecurringRuleService.isDue(rule) {
            pill(text: L10n.Recurring.dueToday, systemImage: "bell.fill")
        }
    }

    private func pill(text: String, systemImage: String) -> some View {
        HStack(spacing: 4) {
            Image(systemName: systemImage)
            Text(text)
        }
        .font(.app(.caption2, weight: .bold))
        .foregroundStyle(.white)
        .padding(.horizontal, 10)
        .padding(.vertical, 5)
        .background(.white.opacity(0.22), in: Capsule())
    }

    // Detail rows on the card body.
    private var details: some View {
        VStack(spacing: 0) {
            if let category = rule.category {
                detailRow(icon: category.icon, iconTint: tint, label: L10n.Transaction.category, value: category.name)
                separator
            }
            if let wallet = rule.wallet {
                detailRow(icon: "wallet.pass.fill", iconTint: .blue, label: "recurring.wallet".localized, value: wallet.name)
                separator
            }
            detailRow(
                icon: "calendar",
                iconTint: .orange,
                label: "recurring.startedOn".localized,
                value: rule.startDate.formatted(date: .abbreviated, time: .omitted)
            )
            if let end = rule.endDate {
                separator
                detailRow(
                    icon: "calendar.badge.exclamationmark",
                    iconTint: .pink,
                    label: "recurring.ends".localized,
                    value: end.formatted(date: .abbreviated, time: .omitted)
                )
            }
        }
        .background(Color(uiColor: .secondarySystemGroupedBackground))
    }

    private func detailRow(icon: String, iconTint: Color, label: String, value: String) -> some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .font(.app(.footnote, weight: .semibold))
                .foregroundStyle(iconTint)
                .frame(width: 30, height: 30)
                .background(iconTint.opacity(0.14), in: RoundedRectangle(cornerRadius: 9, style: .continuous))

            Text(label)
                .font(.app(.subheadline))
                .foregroundStyle(.secondary)

            Spacer(minLength: 12)

            Text(value)
                .font(.app(.subheadline, weight: .semibold))
                .foregroundStyle(.primary)
                .lineLimit(1)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 12)
    }

    private var separator: some View {
        Divider().padding(.leading, 58)
    }
}
